//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class NacladnayaItem
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public Nullable<int> NacladnayaId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Nacladnaya Nacladnaya { get; set; }
        public virtual Product Product { get; set; }
    }
}
